### ISSUE TITLE
Running problems

### ISSUE THREAD

**Issue by traderforce** [dariasor/TreeExtra#8]
Dear author, I use the code for research experiments. But I met problems when running the model training, and the followings are my running ways. Could you help directing my problems or share with me an extra way to run the code. Thanks much!
    
![image](https://user-images.githubusercontent.com/24294874/78205541-f3c3c580-74ce-11ea-9fbd-ea4d767f3fd0.png)

I use sample data from this site. I use visual studio to run the code, and set argv's parameters as follows to run "ag_train". (input the parameters in "Command Arguments")

![image](https://user-images.githubusercontent.com/24294874/78206663-0c81aa80-74d2-11ea-89a2-07d8e2c24de7.png)

Then I met "Error: failed to open attribute file."

![image](https://user-images.githubusercontent.com/24294874/78206758-49e63800-74d2-11ea-9a8c-118cc3d9fbaf.png)

Looking forward to receiving your reply, thanks !

**Comment by dariasor** [comment]
You haven't set up the working directory - right below Command Arguments. So it is looking for the data.attr in the wrong place.

**Comment by traderforce** [comment]
> You haven't set up the working directory - right below Command Arguments. So it is looking for the data.attr in the wrong place.
Got it. Thanks for your help！
